SET IDENTITY_INSERT [dbo].[Activities] ON
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (1, N'Think Leadership 2017', N'2017-06-11 00:00:00', N'Think Leadership este evenimentul dedicat profesionistilor cu experienta in marketing, sales, finance, IT, logistica sau resurse umane care urmaresc sau detin o pozitie de manager. Acesta isi propune sa ofere un spatiu de networking pentru profesionisti si lideri din mediul business de la care tu sa descoperi ce resurse poti accesa pentru dezvoltarea ta profesionala intr-o companie de top.

', N'Conferinta', N'http://www.businessnewsdaily.com/images/i/000/007/894/original/leadership.jpg?1422027258', 60, 6)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (2, N'Mixul dintre Design Thinking & Agile pentru a dezvolta produse orientate spre userii lor', N'2017-06-12 00:00:00', N'Silvia Mihăilescu va modera și va coordona sesiunea dedicată studiilor de caz marca IBM, în contextul dezvoltării produselor centrate pe utilizatori, prin combinarea Design Thinking și a abordării Agile.', N'Training', N'https://image.freepik.com/free-vector/creative-team_23-2147506557.jpg', 120, 7)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (3, N'iCEE.fest', N'2017-06-15 00:00:00', N'iCEE.fest este unul dintre cele mai apreciate evenimente de profil din regiunea Europei Centrale și de Est, devenind un real festival al industriei digitale în cei 5 ani de când a avut loc prima ediție.', N'Conferinta', N'http://www.controlesempresariales.com/es-co/Blog/PublishingImages/caracters03.jpg', 60, 2)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (4, N'Regatta IT', N'2017-09-16 00:00:00', N'Regatta IT anunță anul acesta cea de-a doua ediție a competiției de sailing pentru pasionații de tehnologie. Oameni din companii de IT, care iubesc adrenalina, spiritul competiției și ideea de a socializa într-un mediu informal, sunt așteptați și anul acesta pe mare, la un eveniment dedicat lor: cu distracție, soare, vânt atât cât trebuie! Neapărat în echipă, ca să putem să ocupăm frumos podiumul și clasamentul, dotați cu energie și zâmbete!', N'Competitie', N'https://image.shutterstock.com/z/stock-vector-programmer-and-process-coding-programming-concept-264265364.jpg', 180, 6)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (5, N'FII Practic', N'2017-03-05 00:00:00', N'Proiectul urmăreşte oferirea unor training-uri calitative, moderne şi practice studenţilor şi liceenilor ieşeni, în arii relevante din domeniul IT şi din domeniul project & business management.', N'Training', N'http://360.uaic.ro/wp-content/uploads/2014/01/Sigl%C4%83_FIIPractic.jpg', 120, 1)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (6, N'FII Code', N'2017-03-05 00:00:00', N'Proiectul dorește ca participanții să valorifice abilitățile (și să dezvolte competențe), prin intermediul competiției: gândirea algoritmică și analitică, modelarea și implementarea, dezvoltarea de noi tehnologii, creativitatea, adaptabilitatea, precum  și capacitatea de a susține în public a unei lucrări proprii. Cele 3 secțiuni, Algoritmică, Web și Mobile, sunt concepute special pentru acest lucru, fiecare acoperind o anumită arie din domeniul IT aflată în acest moment în plina expansiune. Modul de organizare al competiției implică cunoașterea atât de noțiuni practice cât și teoretice. ', N'Competitie', N'https://ziar.asii.ro/wp-content/uploads/2017/05/fiicode-300x300.png', 180, 3)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (7, N'STAGII DE PRACTICĂ', N'2017-03-18 00:00:00', N'Programul național de stagiatură Stagii pe Bune propune plasarea studenților facultaților cu profil IT&C în stagii de practică, desfășurate pe durata verii, în companiile din domeniul IT&C. Programul de stagii se află la a treisprezecea ediție și este, și în acest an, programul oficial de stagiatură al celor mai importante centre educaționale IT&C din România: Iași, București.', N'Conferinta', N'http://inventeaza.ro/sites/default/files/styles/news_article_picture/public/stagiipebune.jpg?itok=vcUVbtwe', 60, 4)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (8, N'Training Java', N'2017-07-25 00:00:00', NULL, N'Training', N'https://spzone-simpleprogrammer.netdna-ssl.com/wp-content/uploads/2016/09/Make-the-Most-of-Your-Limited-Willpower-To-Become-a-Better-Programmer-1020x560.png', 180, 1)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (9, N'Training PHP', N'2017-08-10 00:00:00', NULL, N'Training', N'https://previews.123rf.com/images/enotmaks/enotmaks1402/enotmaks140200008/25528506-Flat-illustration-of-programmer-and-process-coding-and-programming-Workflow-and-planning-illustratio-Stock-Vector.jpg', 180, 3)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (10, N'Training Soft Skills', N'2017-07-15 00:00:00', NULL, N'Training', N'https://sites.google.com/site/jacksoncountyschoolswbl/_/rsrc/1472867651252/my-forms/georgiabest-business-ethics-student-training/Top%2010%20soft%20skills.jpg?height=1103&width=734', 180, 6)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (11, N'Chief Data & Analytics Officer Singapore', N'2017-07-26 00:00:00', N'Chief Data and Analytics Officer Singapore is the most comprehensive event for data development, analytics and innovation across the region. Bringing you two full days of insight, conversation and expert-led masterclasses provide excellent opportunity to further expand your knowledge and tool set.', N'Conferinta', N'http://www.dataversity.net/wp-content/uploads/2014/08/cdo.jpg?x23053', 60, 8)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (12, N'FinTech Connect 2017', N'2017-12-06 00:00:00', N'Combining the hustle and bustle of an exhibition featuring over 3000 visitors, and 200 exhibitors and partners from over 50 countries, FinTech Connect Live is the UK’s largest fintech event. Playing host to 4 strategic conference sessions with inspirational case studies from around the world, a technology buyers theatre with 50 product demos, 12 educational workshops tackling practical fast growth challenges, and two full days of dedicated mentoring clinics for start up leaders, all brought to you from over 300 of the industries finest speakers, FinTech Connect Live is the ‘must have ticket’ for stakeholders from across the full fintech eco-system.', N'Conferinta', N'http://cdn.ttgtmedia.com/Marketing/2017/05/FinTech_logo.png', 60, 2)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (13, N'Smarter Business Tech LIVE 2017', N'2017-12-16 00:00:00', N'Introducing Smarter Business Tech LIVE, the brand new 2-day business technology solutions event, designed for the small and mid-size enterprise sector providing crucial knowledge, intelligence and technology/partner options empowering business leaders, C-suite & enterprise decision makers plus departmental and change management. Delivering business growth & success through technology-enabled solutions and partners across all departments including IT, Sales, Marketing, Finance, HR, Logistics, Supply Chain, Commerce, Production, Service, Enterprise Planning… and more', N'Conferinta', N'https://yt3.ggpht.com/-AJRMPswa9J8/AAAAAAAAAAI/AAAAAAAAAAA/11EbN7DTM3w/s900-c-k-no-mo-rj-c0xffffff/photo.jpg', 60, 6)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (14, N'Cloud & DevOps World 2017', N'2017-06-15 00:00:00', N'This year Cloud & DevOps World will be better than ever. It will be part of London Tech Week’s Official expo, TechXLR8. Bringing you industry leading organisations all under one roof. With the likes of Facebook, PayPal, HSBC, Chef and any more.', N'Conferinta', N'https://cdn-az.allevents.in/banners/a63d9f121dfc59f51f4b57cdf91639ce', 60, 9)
INSERT INTO [dbo].[Activities] ([Id], [Name], [StartDate], [Description], [Type], [Image], [Minutes], [Skill_Id]) VALUES (15, N'DataCentre Transformation Manchester (DT Manchester)', N'2017-06-10 02:30:00', N'Now in its seventh year, Data Centre Transformation Manchester (DT Manchester) is organised by Angel Business Communications, in association with Datacentre Solutions, the University of Leeds and the Data Centre Alliance. The combination of such data centre knowledge and expertise ensures that DT Manchester is the premier data centre education event in the calendar, bringing together the data centre research and design community, the data centre vendor industry and, most importantly, enterprise end users, for a collaborative information exchange.', N'Conferinta', N'http://cdn.ttgtmedia.com/Marketing/2017/03/DT%20Manchester%20Logo%202017%20Dated.jpg', 60, 8)
SET IDENTITY_INSERT [dbo].[Activities] OFF
